### ISSUE TITLE
I can't find the publisher of the point_cloud topic

### ISSUE THREAD

**Issue by zhang-mu-zhi** [mmahdavian/semantic_visual_teach_repeat#3]
```
         self.bb_sub = message_filters.Subscriber('/darknet_ros/bounding_boxes', BoundingBoxes)
         self.cam_sub = message_filters.Subscriber('/orb_pose', PoseStamped)
         self.pc_sub = message_filters.Subscriber('/point_cloud', PointCloud )
         self.obj_pub = rospy.Publisher('/obj_position', PointCloud , queue_size=1)         
         self.ts = message_filters.ApproximateTimeSynchronizer([self.bb_sub,self.cam_sub,self.pc_sub], 1, 0.02)
         self.ts.registerCallback(self.gotdata)   

```

In the orb_obj.py file, I only see the subscription to the point_cloud topic, Where is the point_cloud topic published?

**Comment by mmahdavian** [comment]
Hi. Sorry for the late reply. You need to use this ORB_SLAM: https://github.com/mmahdavian/ORB_SLAM3
If you use it will Monocular data, the ros node inside the ORB-SLAM publishes the pointcloud of the environment you are looking for. Good Luck

**Comment by zhang-mu-zhi** [comment]
I found this topic, thank you very much for your answer.
