### ISSUE TITLE
There are some files i can't find

### ISSUE THREAD

**Issue by zhang-mu-zhi** [mmahdavian/semantic_visual_teach_repeat#4]
```
  if c[0] !=0 and c[1] !=0:
             with open('/home/mohammad/Desktop/cur_cam.csv', mode='a') as proj_file:
                 proj_writer = csv.writer(proj_file, delimiter=',')
                 proj_writer.writerow([c[0],c[1],c[2],R[0],R[1],R[2],R[3]])

if new_position[0] !=0 and new_position[1] != 0:
             with open('/home/mohammad/Desktop/new_cam.csv', mode='a') as proj_file:
                 proj_writer = csv.writer(proj_file, delimiter=',')
                 proj_writer.writerow([new_position[0],y2,new_position[1],new_quat[0],new_quat[1],new_quat[2],new_quat[3]])

   cur_cam_file = '/home/mohammad/Desktop/cur_cam.csv'
    if os.path.exists(cur_cam_file):
        os.remove(cur_cam_file)

    new_cam_file = '/home/mohammad/Desktop/new_cam.csv'
    if os.path.exists(new_cam_file):
        os.remove(new_cam_file)

    new_cam_file = '/home/mohammad/Desktop/init_path.csv'
    if os.path.exists(new_cam_file):
        os.remove(new_cam_file)

```
In the relocalization.py file, ralocalization.py needs to call these three files "cur_cam.csv, new_cam.csv, init_path.csv", but I can't find these files.
What should I do?
Thank you very much for your answer.
Thank you very much for your answer.

**Comment by mmahdavian** [comment]
Hi. It doesn't need to call them. It actually tries to create the files during relocalization and repeat path. But at each time, it checks first to see if you have them. If yes, it removes them to create new ones. The only thing you need to change here is the address of the files. Right now they are based on my computer name. Change the "mohammad" part to your computer name and basically give correct address of your desktop to all the address lines. Let me know if you still had any issues
