### ISSUE TITLE
How did you set up the Rviz interface during the teach and repeat stages?

### ISSUE THREAD

**Issue by zhang-mu-zhi** [mmahdavian/semantic_visual_teach_repeat#5]
In the teaching phase, I run the command: roslaunch semantic_visual_teach_repeat create_map.launch, and then a rviz interface will appear, but we don’t know how to set the Displays in this rviz interface, just like you showed in the video.

Can you explain in the README how to set up the Displays of this rviz? Or you can explain how to add Displays parameters below the question.

And can you explain how to set the Displays of rviz in the repeat phase?

You can see what I don't understand about rviz's Displays in the picture below.

![teach](https://user-images.githubusercontent.com/45783556/210365179-b221614c-a945-43cb-be5d-8a7ef8b3f6c0.png)
![repeat](https://user-images.githubusercontent.com/45783556/210365190-f1c2900c-0504-4634-93b3-dbac68f0cfd9.png)

​Thank you very much
Xinhao Zhang

**Comment by mmahdavian** [comment]
Hi Xinhao

Thank you for your interest in my work. I think you can click on add and go to topics and see all the topics that are being published. You can decide what topics do you want to see. For example I think these topics can be useful: 
map_objects,teach_objects_marker_array,teach_camera_marker_array,goal_points_marker_array,camera_pose_marker_array,new_objects_marker_array,new_camera_pose_marker_array, etc.
